tests/e2e_tests: remove synchronous `TestClient`
Due to `fastapi` version change, the newer `TestClient` from
`fastapi` is causing issues by using `anyio` and creating
a different event loop.
This results into failing async pubsub e2e tests with below
errors:
```
RuntimeError: Task got Future attached to a different loop
```
Remove sync test client and use async one for all the tests
to fix it.

Signed-off-by: Jeny Sadadia <jeny.sadadia@collabora.com>