api/main.py: Fix exception when node doesn't exist
If we submit over kci tool node with non-existing ID, then
we will get exception:
```
[api-77fd989c9c-mdzjr]: INFO:     10.244.1.36:55856 - "PUT /latest/node/aaaabbcf8326c545a780f36c HTTP/1.1" 500 Internal Server Error
[api-77fd989c9c-mdzjr]: ERROR:    Exception in ASGI application
[api-77fd989c9c-mdzjr]: Traceback (most recent call last):
...
[api-77fd989c9c-mdzjr]:   File "/home/kernelci/.local/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 550, in solve_dependencies
[api-77fd989c9c-mdzjr]:     solved = await call(**sub_values)
[api-77fd989c9c-mdzjr]:   File "/home/kernelci/.local/lib/python3.10/site-packages/api/main.py", line 130, in authorize_user
[api-77fd989c9c-mdzjr]:     if not user.profile.username == node_from_id.owner:
[api-77fd989c9c-mdzjr]: AttributeError: 'NoneType' object has no attribute 'owner'
```

Signed-off-by: Denys Fedoryshchenko <denys.f@collabora.com>