Add support for Python 3.11
Upgrade Python version to 3.11 for API. Update
docker recipe that is being used for Developer mode
to use `Python 3.11` image.
Update requirements version to enable support for Python 3.11.
Below are the required changes:
1. `httptools` that is a requirement for `uvicorn`, failed to
build for existing package version that was `0.13.4`.
```
gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.11 -I/tmp/pip-install-o_24u7rm/httptools_8955220ea3f34d0bae14ed2b27b468ae/vendor/http-parser -c httptools/parser/parser.c -o build/temp.linux-x86_64-cpython-311/httptools/parser/parser.o -O2
httptools/parser/parser.c:212:12: fatal error: longintrepr.h: No such file or directory
212 |   #include "longintrepr.h"
    |            ^~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for httptools
```
Fix it by using `uvicorn` version with Python 3.11 support i.e. `0.29.0`.
2. Since `uvicorn` is one of the requirements of `fastapi`, we
also need to update its version to make it compatible with `uvicorn`.
The fastapi version `0.99.1` has been selected to avoid dependency conflicts with
existing `fastapi-users` version i.e. `10.4.0`. Otherwise the below build failure
will take place:
```
ERROR: Cannot install fastapi-users, fastapi-users[beanie,oauth]==10.4.0 and fastapi[all]==0.110.0 because
these package versions have conflicting dependencies.
```
3. `fastapi==0.99.1` also removes the requirement of pinning `pyyaml` version.
Dropped: 473bd7b ("docker/api: pin PyYAML version to 5.3.1")
4. Also, upgrade `motor` version to use it with python 3.11.
5. Upgrade `pylint` to the latest version i.e. `3.1.0`to resolve
below incompatibility issue from `wrapt` package:
```
File "/usr/local/lib/python3.11/site-packages/wrapt/decorators.py", line 34, in <module>
    from inspect import ismethod, isclass, formatargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/local/lib/python3.11/inspect.py)
```

Signed-off-by: Jeny Sadadia <jeny.sadadia@collabora.com>