fix(workflows): Fix broken workflows
All of sudden workflows are not working anymore,
as docker-compose is missing.

```
Run docker-compose -f test-docker-compose.yaml down
/home/runner/work/_temp/99b8e55a-c49f-4174-934d-3578b404c126.sh: line 1: docker-compose: command not found
Error: Process completed with exit code 127.
```

Signed-off-by: Denys Fedoryshchenko <denys.f@collabora.com>